version: '3'

services:

  cow:
    image: golang:1.9-alpine
    build: .
    ports:
    - 8080:8080
    volumes:
    - ./:/go/src/github.com/georgizhivankin/go-slacking-cow
    links:
    - mongo
    depends_on:
    - mongo
    networks:
    - webstack
    
  mongo:
    image: mongo:3
    environment:
    - DATABASE_DSN=mongo
    - DATABASE_PORT=27017
    - DATABASE_NAME=cow
    ports:
    - 27017
    volumes:
    - mongo:/data/db
    networks:
    - webstack
    
volumes:
  mongo:
    driver: local
    
networks:
  webstack:
    driver: bridge